# Generated by Django 4.1.4 on 2022-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Notebooks', 'Notebooks'), ('PCs', 'PCs'), ('Monitors', 'Monitors'), ('Mouses', 'Mouses'), ('Keyboards', 'Keyboards'), ('Headphones', 'Headphones')], default=None, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
