# Generated by Django 4.1.4 on 2022-12-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('proteina', 'proteina'), ('guante', 'guante'), ('bebida', 'bebida')], default=None, max_length=200),
        ),
    ]
