# Generated by Django 4.1.4 on 2023-01-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_at',
        ),
    ]
