# Generated by Django 4.1.4 on 2023-01-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creater_at',
            new_name='created_at',
        ),
    ]
